import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

test('PostgreSQL: POA, ownership, entitlement, progression, edits, AI separation and revocation', async () => {
  const db = new PGlite();
  const creator='11111111-1111-4111-8111-111111111111', other='22222222-2222-4222-8222-222222222222';
  const assessment='33333333-3333-4333-8333-333333333333', report='44444444-4444-4444-8444-444444444444';
  async function role(name: string, id='') { await db.exec(`reset role; select set_config('request.jwt.claim.sub','${id}',false); set role ${name};`); }
  async function call<T=any>(sql: string, params: unknown[] = []): Promise<T> { const result=await db.query(sql,params); return Object.values(result.rows[0] as object)[0] as T; }
  try {
    // Only existing prerequisite contracts are stubbed; new migration/functions run unchanged.
    await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth; create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      grant usage on schema auth to anon,authenticated,service_role; grant execute on function auth.uid() to public;
      create table creator_profiles(id uuid primary key,auth_user_id uuid,full_name text,email text);
      create function is_agency() returns boolean language sql as $$ select current_setting('request.jwt.claim.sub',true)='99999999-9999-4999-8999-999999999999' $$;
      create function current_creator_profile_id() returns uuid language sql security definer as $$ select id from creator_profiles where auth_user_id=auth.uid() $$;
      create table creator_assessments(id uuid primary key,creator_profile_id uuid,answers jsonb,responses jsonb);
      create table creator_reports(id uuid primary key,creator_profile_id uuid,assessment_id uuid,report_slug text,report_json jsonb,created_at timestamptz default now());
      create table commercial_catalogue_product(product_id text,code text,lifecycle_status text);
      create table commercial_catalogue_plan(plan_id text,product_id text,is_sellable boolean,sort_order int);
      create table commercial_catalogue_plan_price_version(plan_version_id text,plan_id text,status text,price jsonb,effective_from timestamptz,effective_to timestamptz,version int);
      insert into creator_profiles(id,auth_user_id) values('${creator}','${creator}'),('${other}','${other}');
      insert into creator_assessments values('${assessment}','${creator}','{"comfort_level":8}','{}');
      insert into creator_reports values('${report}','${creator}','${assessment}','test-report','{}',now());`);
    await db.exec(readFileSync(new URL('../supabase/migrations/20260915041632_fyv_personal_vertical_plan.sql',import.meta.url),'utf8'));
    await role('anon');
    await assert.rejects(()=>call('select fyv_get_plan_access()'),/permission denied/);
    await role('authenticated',creator);
    assert.equal((await call('select fyv_get_plan_access()')).entitled,false);
    await assert.rejects(()=>call('select fyv_list_plan_requests()'),/agency access required/);
    await assert.rejects(()=>call('select fyv_open_personal_plan()'),/paid plan/);
    const interest=await call('select fyv_request_personal_plan($1)',['test-report']);
    assert.equal(interest.catalogue_status,'pending_configuration');
    assert.equal((await call('select fyv_request_personal_plan($1)',['test-report'])).id,interest.id);
    assert.equal((await call('select fyv_get_plan_access()')).entitled,false);
    await assert.rejects(()=>db.exec('select * from fyv_plan_entitlements'),/permission denied/);
    await assert.rejects(()=>call('select fyv_project_plan_commercial($1,1,$2,$3,12000,$4)',[interest.id,'quoted','poa','NZD']),/permission denied/);
    await role('service_role');
    await call('select fyv_project_plan_commercial($1,2,$2,$3,12000,$4)',[interest.id,'quoted','fixed','NZD']);
    await call('select fyv_project_plan_commercial($1,1,$2,$3)',[interest.id,'reviewing','poa']);
    await role('authenticated',creator);
    const commercial = await call('select fyv_get_plan_access()');
    assert.equal(commercial.interest.status,'quoted');
    assert.equal(commercial.interest.price_kind,'fixed');
    assert.equal(commercial.interest.amount_minor,12000);
    assert.equal(commercial.interest.currency,'NZD');
    assert.equal(commercial.entitled,false, 'commercial status never grants paid access');
    await assert.rejects(()=>call('select fyv_project_plan_entitlement($1,$2,1,$3,now()+interval \'1 day\')',[creator,'grant','active']),/permission denied/);
    await role('service_role');
    await call('select fyv_project_plan_entitlement($1,$2,1,$3,now()+interval \'1 day\')',[creator,'grant','active']);
    await role('authenticated',creator);
    const opened=await call('select fyv_open_personal_plan()'); const plan=opened.plan.id;
    assert.equal(opened.plan.assessment_id,assessment);
    assert.equal((await call('select fyv_open_personal_plan()')).plan.id,plan);
    await assert.rejects(()=>call('select fyv_save_plan_stage($1,$2,$3,0,false)',[plan,'audience','{}']),/previous stages/);
    await assert.rejects(()=>call('select fyv_save_plan_stage($1,$2,$3,0,false)',[plan,'direction','{"unknown":"x"}']),/invalid field/);
    const direction={vertical:'Fitness',reason:'My interest',boundaries:'No explicit material'};
    await call('select fyv_save_plan_stage($1,$2,$3,0,true)',[plan,'direction',JSON.stringify(direction)]);
    await assert.rejects(()=>call('select fyv_save_plan_stage($1,$2,$3,0,true)',[plan,'direction',JSON.stringify(direction)]),/Plan changed/);
    const req=await call('select fyv_reserve_plan_guidance($1,$2,1)',[plan,'direction']);
    await role('service_role');
    await call('select fyv_complete_plan_guidance($1,$2,$3,$4,$5,$6)',[req,'refine','{}','{"vertical":"AI idea"}','test','test']);
    await role('authenticated',creator);
    const suggested=await call('select fyv_open_personal_plan()');
    assert.equal(suggested.stages[0].data.vertical,'Fitness'); assert.equal(suggested.suggestions.length,1);
    await call('select fyv_save_plan_stage($1,$2,$3,1,true,$4)',[plan,'direction',JSON.stringify({...direction,vertical:'Creator edited AI idea'}),req]);
    const updated=await call('select fyv_open_personal_plan()'); assert.equal(updated.stages[0].revision,2);
    assert.equal(updated.stages[0].data.vertical,'Creator edited AI idea'); assert.equal(updated.assessment.answers.comfort_level,8);
    await role('authenticated',other);
    await assert.rejects(()=>call('select fyv_request_personal_plan($1)',['test-report']),/Complete an assessment/);
    await assert.rejects(()=>call('select fyv_save_plan_stage($1,$2,$3,2,true)',[plan,'direction',JSON.stringify(direction)]),/paid plan/);
    await role('service_role');
    await call('select fyv_project_plan_entitlement($1,$2,1,$3,now()+interval \'1 day\')',[other,'other-grant','active']);
    await role('authenticated',other);
    await assert.rejects(()=>call('select fyv_save_plan_stage($1,$2,$3,2,true)',[plan,'direction',JSON.stringify(direction)]),/paid plan/);
    await role('service_role');
    await call('select fyv_project_plan_entitlement($1,$2,2,$3,now()+interval \'1 day\')',[creator,'grant','revoked']);
    await call('select fyv_project_plan_entitlement($1,$2,1,$3,now()+interval \'1 day\')',[creator,'grant','active']);
    await role('authenticated',creator);
    assert.equal((await call('select fyv_get_plan_access()')).entitled,false);
    await assert.rejects(()=>call('select fyv_open_personal_plan()'),/paid plan/);
    await role('service_role');
    await assert.rejects(()=>call('select fyv_complete_plan_guidance($1,$2,$3,$4,$5,$6)',[req,'refine','{}','{"vertical":"late"}','test','test']),/paid plan/);
    await role('postgres');
    assert.equal(await call('select count(*)::int from fyv_plan_stage_revisions'),2);
    assert.equal(await call('select count(*)::int from creator_assessments'),1);
    await db.exec(`insert into commercial_catalogue_product values('real-product','FYV-PERSONAL-VERTICAL-PLAN','published');
      insert into commercial_catalogue_plan values('real-offer','real-product',true,1);
      insert into commercial_catalogue_plan_price_version values('real-price','real-offer','published','{"kind":"poa"}',now(),null,1);
      insert into creator_assessments values('55555555-5555-4555-8555-555555555555','${other}','{}','{}');
      insert into creator_reports values('66666666-6666-4666-8666-666666666666','${other}','55555555-5555-4555-8555-555555555555','other-report','{}',now());`);
    await role('authenticated',other);
    assert.equal((await call('select fyv_request_personal_plan($1)',['other-report'])).catalogue_status,'resolved');
    const second=await call('select fyv_open_personal_plan()');
    const definitions=[['direction',['vertical','reason','boundaries']],['audience',['audience','needs','evidenceToGather']],['positioning',['promise','difference','bio']],['content',['pillars','channels','formats']],['offers',['offer','sellingApproach','demandTest']],['schedule',['weeklyHours','publishingSchedule','batching']],['scripts',['hook','outline','callToAction']],['experiments',['hypothesis','measure','reviewDate']],['final',['milestones','nextActions','reviewDate']]] as const;
    for(const [key,fields] of definitions) await call('select fyv_save_plan_stage($1,$2,$3,0,true)',[second.plan.id,key,JSON.stringify(Object.fromEntries(fields.map(f=>[f,'Creator decision'])))]);
    assert.equal((await call('select fyv_open_personal_plan()')).plan.status,'complete');
    for(let i=0;i<20;i++) await call('select fyv_reserve_plan_guidance($1,$2,1)',[second.plan.id,'final']);
    await assert.rejects(()=>call('select fyv_reserve_plan_guidance($1,$2,1)',[second.plan.id,'final']),/Daily guidance limit/);
    await role('service_role');
    await call('select fyv_project_plan_entitlement($1,$2,2,$3,now()-interval \'1 second\')',[other,'other-grant','active']);
    await role('authenticated',other);
    assert.equal((await call('select fyv_get_plan_access()')).entitled,false);
    await role('authenticated','99999999-9999-4999-8999-999999999999');
    assert.equal((await call('select fyv_list_plan_requests()')).length,2);
  } finally { await db.close(); }
});
