// ─────────────────────────────────────────────────────────────────────────────
// Creator Intelligence — Knowledge Registry: Opportunities (Sprint FYV-3.4B)
//
// Commercial opportunity catalogue. 16 entries, each tagged by conditions,
// evidence, expected outcome, recommended actions, and related
// archetypes/verticals/traits.
//
// An empty relatedness array means the opportunity is universally relevant.
// ─────────────────────────────────────────────────────────────────────────────

import type { Opportunity } from './types';

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-001',
    title: 'Premium custom content pipeline',
    description: 'High-value custom content commissions from fans willing to pay for bespoke, personalised creations.',
    applicableConditions: ['Monetisation readiness is Ready or Advanced', 'Fan connection is strong', 'Archetype supports custom work'],
    supportingEvidence: ['monetisation_fit trait weight above 60', 'fan_connection trait weight above 55', 'Archetype includes roleplay or character work'],
    expectedOutcome: 'Unlocks a high-margin revenue stream with repeat-purchase potential.',
    recommendedActions: ['Define a priced custom menu with 3-5 tiers', 'Set clear delivery timelines and boundaries', 'Track top custom buyers for re-engagement'],
    priority: 'high',
    relatedArchetypes: ['Hot Teacher', 'Cosplayer', 'Dominatrix', 'Naughty Librarian', 'Nurse', 'Doctor'],
    relatedVerticals: ['Roleplay / Character Content', 'Tease & Deny'],
    relatedTraits: ['monetisation_fit', 'fan_connection', 'positioning_clarity'],
  },
  {
    id: 'opp-002',
    title: 'Whale-focused VIP programme',
    description: 'Structured VIP tier targeting high-spend fans with exclusivity, priority access, and personalised attention.',
    applicableConditions: ['Audience strategy is whales', 'Brand clarity score above 55'],
    supportingEvidence: ['Audience strategy is whales', 'Monetisation readiness is Ready or Advanced'],
    expectedOutcome: 'Concentrates revenue from the highest-value segment with strong retention.',
    recommendedActions: ['Launch a capped VIP tier at 3-5x base price', 'Deliver exclusive content and priority DMs', 'Personally onboard each VIP member'],
    priority: 'high',
    relatedArchetypes: ['Luxury Muse', 'Rich Girl', 'Trophy Wife', 'High-Class Escort Fantasy', 'Dominatrix', 'Soft Girlfriend Experience'],
    relatedVerticals: ['Editorial / High-Fashion Shoots', 'Tease & Deny'],
    relatedTraits: ['monetisation_fit', 'positioning_clarity', 'trust_building'],
  },
  {
    id: 'opp-003',
    title: 'Cross-platform subscriber acquisition',
    description: 'Use mainstream social platforms to drive traffic to the subscription page, expanding discovery beyond the primary platform.',
    applicableConditions: ['visibility_comfort is strong', 'Content has mainstream-safe crossover potential'],
    supportingEvidence: ['visibility_comfort trait weight above 60', 'social_energy trait weight above 55'],
    expectedOutcome: 'Increases top-of-funnel reach and reduces dependence on a single discovery source.',
    recommendedActions: ['Establish 1-2 mainstream profiles with safe, teaser content', 'Link clearly to subscription page', 'Track conversion from each platform'],
    priority: 'high',
    relatedArchetypes: ['Fitness Goddess', 'Gamer Girl', 'College Girl', 'Party Girl', 'Boss Babe'],
    relatedVerticals: ['Fitness Journey', 'Lifestyle Vlogging / GRWM', 'Comedy Skits'],
    relatedTraits: ['visibility_comfort', 'social_energy'],
  },
  {
    id: 'opp-004',
    title: 'Recurring content series monetisation',
    description: 'Transform a popular recurring format into a paid series with tiered access or PPV episodes.',
    applicableConditions: ['Creator has at least one recurring format with engagement', 'Consistency score above 55'],
    supportingEvidence: ['routine_discipline trait weight above 55', 'Consistency score above 50'],
    expectedOutcome: 'Converts existing engagement patterns into predictable recurring revenue.',
    recommendedActions: ['Identify your highest-engagement recurring format', 'Gate premium episodes behind PPV or tiers', 'Maintain the free cadence as a funnel'],
    priority: 'medium',
    relatedArchetypes: [],
    relatedVerticals: ['Polarizing Storytimes', 'Skill-Based Challenges', 'Confessional Storytime'],
    relatedTraits: ['routine_discipline', 'monetisation_fit'],
  },
  {
    id: 'opp-005',
    title: 'DM monetisation scaling',
    description: 'Scale direct messaging revenue through templated sequences, upsell pathways, and mass-personalised broadcasts.',
    applicableConditions: ['Fan connection trait is strong', 'DMs are a significant engagement channel'],
    supportingEvidence: ['fan_connection trait weight above 60', 'trust_building trait weight above 55'],
    expectedOutcome: 'Increases DM revenue per hour invested through efficiency and structure.',
    recommendedActions: ['Build a template library for common DM interactions', 'Create upsell sequences triggered by engagement', 'Use mass messages with personalisation tokens'],
    priority: 'high',
    relatedArchetypes: ['Soft Girlfriend Experience', 'Girl Next Door', 'Nurse', 'Brat'],
    relatedVerticals: ['Cosy Authenticity'],
    relatedTraits: ['fan_connection', 'trust_building', 'monetisation_fit'],
  },
  {
    id: 'opp-006',
    title: 'Collaboration content partnerships',
    description: 'Partner with complementary creators for joint content, cross-promotion, and shared audience exposure.',
    applicableConditions: ['Visibility comfort is moderate or higher', 'Archetype has collaboration-friendly positioning'],
    supportingEvidence: ['visibility_comfort trait weight above 50', 'social_energy trait weight above 45'],
    expectedOutcome: 'Exposes both creators to new audiences, accelerating subscriber growth.',
    recommendedActions: ['Identify 2-3 complementary creators (adjacent archetype, similar audience size)', 'Plan a joint content piece with shared promotion', 'Cross-promote with clear subscribe CTAs'],
    priority: 'medium',
    relatedArchetypes: ['Party Girl', 'Fitness Goddess', 'College Girl', 'Gamer Girl', 'Brat'],
    relatedVerticals: ['Skill-Based Challenges', 'Comedy Skits', 'Fitness Journey'],
    relatedTraits: ['social_energy', 'visibility_comfort'],
  },
  {
    id: 'opp-007',
    title: 'Seasonal and event-driven content drops',
    description: 'Create themed content tied to holidays, cultural events, or seasonal moments for natural promotion spikes.',
    applicableConditions: ['Creator has visual discipline or production capability'],
    supportingEvidence: ['visual_discipline trait weight above 50', 'routine_discipline trait weight above 45'],
    expectedOutcome: 'Drives promotional spikes in subscriber acquisition and PPV sales around events.',
    recommendedActions: ['Plan a content calendar around 4-6 key dates per year', 'Pre-produce themed content in batches', 'Promote with countdown and scarcity mechanics'],
    priority: 'medium',
    relatedArchetypes: ['Cosplayer', 'Luxury Muse', 'Party Girl', 'Fitness Goddess'],
    relatedVerticals: ['Editorial / High-Fashion Shoots', 'Roleplay / Character Content'],
    relatedTraits: ['visual_discipline', 'routine_discipline'],
  },
  {
    id: 'opp-008',
    title: 'Subscription bundle and discount strategy',
    description: 'Offer time-based bundles (3-month, 6-month) at a discount to lock in revenue and reduce monthly churn.',
    applicableConditions: ['Audience strategy is masses or mixed', 'Retention is a priority'],
    supportingEvidence: ['Audience strategy is masses', 'Consistency score above 50'],
    expectedOutcome: 'Reduces monthly churn by converting subscribers to longer commitments.',
    recommendedActions: ['Offer 3-month bundles at 15-20% discount', 'Promote bundles during high-engagement periods', 'Make the long-term value proposition clear'],
    priority: 'medium',
    relatedArchetypes: [],
    relatedVerticals: [],
    relatedTraits: ['monetisation_fit', 'routine_discipline'],
  },
  {
    id: 'opp-009',
    title: 'Wishlist and gifting revenue',
    description: 'Leverage fan gifting culture through wishlists, tribute mechanics, and gifting-occasion content.',
    applicableConditions: ['Archetype supports luxury or aspirational positioning', 'Fan base includes generous spenders'],
    supportingEvidence: ['Archetype is luxury-adjacent', 'Audience strategy is whales'],
    expectedOutcome: 'Opens a non-content revenue stream driven by fan generosity and status signalling.',
    recommendedActions: ['Curate a themed wishlist that fits your brand', 'Create content acknowledging gifts (fuels more gifting)', 'Time pushes around holidays and milestones'],
    priority: 'low',
    relatedArchetypes: ['Trophy Wife', 'Rich Girl', 'Luxury Muse', 'Dominatrix', 'Bimbo'],
    relatedVerticals: [],
    relatedTraits: ['monetisation_fit', 'positioning_clarity'],
  },
  {
    id: 'opp-010',
    title: 'Re-engagement campaign for churned subscribers',
    description: 'Win back lapsed subscribers with targeted re-engagement offers, exclusive return incentives, and "what you missed" content.',
    applicableConditions: ['Creator has been active for 60+ days', 'Has experienced subscriber churn'],
    supportingEvidence: ['Consistency score above 50', 'fan_connection trait weight above 45'],
    expectedOutcome: 'Recovers lost revenue by converting previously interested fans back to active subscribers.',
    recommendedActions: ['Identify lapsed subscribers from platform analytics', 'Send a personalised "miss you" message with an offer', 'Create a "best of" highlight to show what they missed'],
    priority: 'medium',
    relatedArchetypes: [],
    relatedVerticals: [],
    relatedTraits: ['fan_connection', 'monetisation_fit'],
  },
  {
    id: 'opp-011',
    title: 'Authority-premium positioning',
    description: 'Leverage expertise, professionalism, or authority persona to justify premium pricing above market average.',
    applicableConditions: ['Archetype carries authority or expertise positioning', 'Creator communicates confidently'],
    supportingEvidence: ['positioning_clarity trait weight above 60', 'Archetype involves authority dynamic'],
    expectedOutcome: 'Justifies above-market pricing and attracts fans who value quality over volume.',
    recommendedActions: ['Anchor pricing 2-3x above generic competitors', 'Emphasise expertise and exclusivity in positioning', 'Deliver quality that validates the premium'],
    priority: 'high',
    relatedArchetypes: ['Doctor', 'Hot Teacher', 'Boss Babe', 'Dominatrix', 'Luxury Muse'],
    relatedVerticals: ['Editorial / High-Fashion Shoots'],
    relatedTraits: ['positioning_clarity', 'monetisation_fit', 'visibility_comfort'],
  },
  {
    id: 'opp-012',
    title: 'Community-driven content co-creation',
    description: 'Involve fans in content decisions through polls, voting, and co-creation mechanics that increase investment.',
    applicableConditions: ['Fan connection is strong', 'Audience is engaged and interactive'],
    supportingEvidence: ['fan_connection trait weight above 55', 'social_energy trait weight above 50'],
    expectedOutcome: 'Increases engagement, retention, and content relevance by giving fans ownership.',
    recommendedActions: ['Run weekly content polls', 'Create a "fan choice" recurring segment', 'Credit participating fans to encourage more input'],
    priority: 'medium',
    relatedArchetypes: ['Gamer Girl', 'Brat', 'Girl Next Door', 'College Girl'],
    relatedVerticals: ['Skill-Based Challenges', 'Comedy Skits', 'Polarizing Storytimes'],
    relatedTraits: ['fan_connection', 'social_energy'],
  },
  {
    id: 'opp-013',
    title: 'Niche dominance strategy',
    description: 'Become the definitive creator in a specific niche by owning the positioning, keywords, and community.',
    applicableConditions: ['Archetype has clear niche potential', 'Brand clarity is strong'],
    supportingEvidence: ['positioning_clarity trait weight above 65', 'Brand clarity score above 60'],
    expectedOutcome: 'Reduces competition and becomes the default choice for fans seeking this specific niche.',
    recommendedActions: ['Research and own niche-specific keywords and hashtags', 'Create a content library that defines the niche', 'Engage with and lead the niche community'],
    priority: 'high',
    relatedArchetypes: ['Dominatrix', 'Cosplayer', 'Fitness Goddess', 'Spiritual Goddess', 'Alternative / Tattooed'],
    relatedVerticals: ['Roleplay / Character Content', 'Fitness Journey'],
    relatedTraits: ['positioning_clarity', 'routine_discipline'],
  },
  {
    id: 'opp-014',
    title: 'Storytelling-to-subscription funnel',
    description: 'Use compelling narrative content on social platforms to hook audiences and convert them into subscribers.',
    applicableConditions: ['Creator has storytelling ability', 'Content has narrative hook potential'],
    supportingEvidence: ['authenticity trait weight above 55', 'visibility_comfort trait weight above 50'],
    expectedOutcome: 'Converts narrative engagement into paid subscriptions through curiosity and connection.',
    recommendedActions: ['Post story teasers on social with "full story on my page" CTAs', 'Build serial narratives that reward subscription', 'Use cliffhangers strategically'],
    priority: 'medium',
    relatedArchetypes: ['Corporate Rebel', 'Single Mom', 'Girl Next Door'],
    relatedVerticals: ['Polarizing Storytimes', 'Confessional Storytime'],
    relatedTraits: ['authenticity', 'visibility_comfort', 'fan_connection'],
  },
  {
    id: 'opp-015',
    title: 'Transformation and progress content arc',
    description: 'Document a visible transformation journey (fitness, style, confidence) that gives fans a reason to follow over time.',
    applicableConditions: ['Creator is on a visible journey', 'Content has before/after potential'],
    supportingEvidence: ['body_confidence or visibility_comfort is growing', 'routine_discipline trait weight above 50'],
    expectedOutcome: 'Creates a compelling long-term follow reason and strengthens parasocial investment.',
    recommendedActions: ['Document starting point publicly', 'Post regular progress updates on a schedule', 'Celebrate milestones to drive engagement spikes'],
    priority: 'medium',
    relatedArchetypes: ['Fitness Goddess', 'Other', 'College Girl'],
    relatedVerticals: ['Fitness Journey', 'Lifestyle Vlogging / GRWM'],
    relatedTraits: ['body_confidence', 'routine_discipline', 'visibility_comfort'],
  },
  {
    id: 'opp-016',
    title: 'Agency management candidacy',
    description: 'Creator shows strong indicators for professional agency management — structured support could accelerate growth significantly.',
    applicableConditions: ['Agency opportunity score above 65', 'Monetisation readiness is Ready or Advanced', 'Coachability is strong'],
    supportingEvidence: ['agency_opportunity_score above 65', 'coachability trait weight above 60', 'Monetisation readiness is Ready or Advanced'],
    expectedOutcome: 'Professional management unlocks growth, operational efficiency, and higher revenue.',
    recommendedActions: ['Present agency services and value proposition', 'Offer a strategy consultation', 'Outline a 90-day management plan'],
    priority: 'high',
    relatedArchetypes: [],
    relatedVerticals: [],
    relatedTraits: ['coachability', 'monetisation_fit', 'routine_discipline'],
  },
];

/** Opportunity map keyed by id for O(1) lookup. */
export const OPPORTUNITY_MAP: Record<string, Opportunity> = Object.fromEntries(
  OPPORTUNITIES.map(o => [o.id, o])
);
