-- Historical migration retained for Supabase migration-history compatibility.
--
-- The original function definition referenced public.creator_relationships
-- before that table was created, causing fresh database and shadow database
-- rebuilds to fail.
--
-- The canonical creator_relationships table and the complete
-- create_creator_access_invitation function are created in:
-- 20260714000000_fyv_creator_relationship_access.sql
--
-- Intentionally no-op.
