begin;

create table if not exists public.fyv_event_emit_failures (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),

  wrapper_name text not null,
  event_type text,
  entity_type text,
  entity_id uuid,
  source_system text,
  event_status text,
  entity_ref text,
  correlation_id text,
  payload jsonb not null default '{}'::jsonb,

  sqlstate text,
  error_message text,
  error_detail text,
  error_hint text,
  exception_context text
);

create index if not exists fyv_event_emit_failures_created_at_idx
  on public.fyv_event_emit_failures (created_at desc);

create index if not exists fyv_event_emit_failures_wrapper_created_idx
  on public.fyv_event_emit_failures (wrapper_name, created_at desc);

alter table public.fyv_event_emit_failures enable row level security;

revoke all on table public.fyv_event_emit_failures from public;
revoke all on table public.fyv_event_emit_failures from anon;
revoke all on table public.fyv_event_emit_failures from authenticated;

grant all on table public.fyv_event_emit_failures to service_role;
grant usage, select on sequence public.fyv_event_emit_failures_id_seq to service_role;

create or replace function public.fyv_record_event_emit_failure(
  p_wrapper_name text,
  p_event_type text,
  p_entity_type text,
  p_entity_id uuid,
  p_source_system text,
  p_status text,
  p_entity_ref text,
  p_correlation_id text,
  p_payload jsonb,
  p_sqlstate text,
  p_error_message text,
  p_error_detail text,
  p_error_hint text,
  p_exception_context text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.fyv_event_emit_failures (
    wrapper_name,
    event_type,
    entity_type,
    entity_id,
    source_system,
    event_status,
    entity_ref,
    correlation_id,
    payload,
    sqlstate,
    error_message,
    error_detail,
    error_hint,
    exception_context
  )
  values (
    p_wrapper_name,
    p_event_type,
    p_entity_type,
    p_entity_id,
    p_source_system,
    p_status,
    p_entity_ref,
    p_correlation_id,
    coalesce(p_payload, '{}'::jsonb),
    p_sqlstate,
    p_error_message,
    p_error_detail,
    p_error_hint,
    p_exception_context
  );
exception when others then
  raise warning
    'Unable to record FYV event emission failure for wrapper %: [%] %',
    p_wrapper_name,
    sqlstate,
    sqlerrm;
end;
$$;

revoke all on function public.fyv_record_event_emit_failure(
  text,
  text,
  text,
  uuid,
  text,
  text,
  text,
  text,
  jsonb,
  text,
  text,
  text,
  text,
  text
) from public;

grant execute on function public.fyv_record_event_emit_failure(
  text,
  text,
  text,
  uuid,
  text,
  text,
  text,
  text,
  jsonb,
  text,
  text,
  text,
  text,
  text
) to service_role;

create or replace function public.fyv_emit_onboarding_event(
  p_event_type text,
  p_creator_profile_id uuid,
  p_case_id uuid,
  p_payload jsonb
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_sqlstate text;
  v_message text;
  v_detail text;
  v_hint text;
  v_context text;
  v_entity_ref text := 'creator_profile:' || p_creator_profile_id::text;
begin
  begin
    perform public.fyv_emit_event(
      p_event_type,
      'creator_onboarding_case',
      p_case_id,
      p_payload,
      'findyourvertical',
      null,
      v_entity_ref,
      null
    );
  exception when others then
    get stacked diagnostics
      v_sqlstate = returned_sqlstate,
      v_message = message_text,
      v_detail = pg_exception_detail,
      v_hint = pg_exception_hint,
      v_context = pg_exception_context;

    perform public.fyv_record_event_emit_failure(
      'fyv_emit_onboarding_event',
      p_event_type,
      'creator_onboarding_case',
      p_case_id,
      'findyourvertical',
      null,
      v_entity_ref,
      null,
      p_payload,
      v_sqlstate,
      v_message,
      v_detail,
      v_hint,
      v_context
    );
  end;
end;
$$;

revoke all on function public.fyv_emit_onboarding_event(
  text,
  uuid,
  uuid,
  jsonb
) from public;

grant execute on function public.fyv_emit_onboarding_event(
  text,
  uuid,
  uuid,
  jsonb
) to service_role;

create or replace function public.fyv_emit_persona_event(
  p_event_type text,
  p_creator_profile_id uuid,
  p_generation_id uuid,
  p_status text,
  p_payload jsonb
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_sqlstate text;
  v_message text;
  v_detail text;
  v_hint text;
  v_context text;
  v_entity_ref text := 'creator_profile:' || p_creator_profile_id::text;
begin
  begin
    perform public.fyv_emit_event(
      p_event_type,
      'creator_persona_generation',
      p_generation_id,
      p_payload,
      'findyourvertical',
      p_status,
      v_entity_ref,
      null
    );
  exception when others then
    get stacked diagnostics
      v_sqlstate = returned_sqlstate,
      v_message = message_text,
      v_detail = pg_exception_detail,
      v_hint = pg_exception_hint,
      v_context = pg_exception_context;

    perform public.fyv_record_event_emit_failure(
      'fyv_emit_persona_event',
      p_event_type,
      'creator_persona_generation',
      p_generation_id,
      'findyourvertical',
      p_status,
      v_entity_ref,
      null,
      p_payload,
      v_sqlstate,
      v_message,
      v_detail,
      v_hint,
      v_context
    );
  end;
end;
$$;

revoke all on function public.fyv_emit_persona_event(
  text,
  uuid,
  uuid,
  text,
  jsonb
) from public;

grant execute on function public.fyv_emit_persona_event(
  text,
  uuid,
  uuid,
  text,
  jsonb
) to service_role;

commit;
