-- Historical migration retained for Supabase migration-history compatibility.
--
-- The original statements altered creator invitation functions before those
-- functions and their dependent tables were created.
--
-- The canonical functions are created in:
-- 20260714000000_fyv_creator_relationship_access.sql
--
-- Their corrected search paths are defined there.
--
-- Intentionally no-op.